apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  namespace: default
  name: perm-1
spec:
  sources:
    - match:
        service: '*'
  destinations:
    - match:
        service: '*'
