name: docker-build-push

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          file: ./api/Dockerfile
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kuma-demo-be:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          file: ./app/Dockerfile
          context: ./app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kuma-demo-fe:latest

      - name: Build and push postgres
        uses: docker/build-push-action@v5
        with:
          file: ./api/db/postgresql/Dockerfile
          context: ./api/db/postgresql
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest

      - name: Build and push redis
        uses: docker/build-push-action@v5
        with:
          file: ./api/db/redis/Dockerfile
          context: ./api/db/redis
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kuma-redis:latest